<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <AssemblyName>Main</AssemblyName>
        <RootNamespace>ModHandler</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="ASL">
            <HintPath>..\..\BepInEx\plugins\ASL.dll</HintPath>
        </Reference>

        <Reference Include="ASL.API">
            <HintPath>..\..\BepInEx\plugins\ASL.API.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>